/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jniDemo2_MyJniTest */

#ifndef _Included_com_example_jniDemo2_MyJniTest
#define _Included_com_example_jniDemo2_MyJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jniDemo2_MyJniTest
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniDemo2_MyJniTest_getKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
